// frontend_angular/src/app/components/ui/portfolio-advice.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PortfolioAllocation } from '../../models/dashboard.models';

@Component({
  selector: 'app-portfolio-advice',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-[#0f172a] rounded-xl border border-slate-800 p-6 shadow-xl flex flex-col gap-4">
      <div class="flex items-center gap-2 border-b border-slate-800 pb-4">
        <div class="text-emerald-500 font-bold">&#36;</div>
        <h3 class="font-display text-xl tracking-wider text-slate-100 uppercase">Portfolio Strategy</h3>
      </div>
      
      <div class="space-y-4">
        @for (item of suggestions; track item.asset_class) {
          <div class="p-4 rounded-lg bg-slate-900/40 border border-slate-800/50">
            <div class="flex justify-between items-center mb-1">
              <span class="text-xs font-bold text-slate-200 uppercase tracking-tight">{{ item.asset_class }}</span>
              <span class="text-sm font-display text-emerald-400">{{ item.percentage }}</span>
            </div>
            <p class="text-[10px] text-slate-500 italic leading-relaxed">{{ item.rationale }}</p>
          </div>
        }
      </div>

      <div class="mt-4 pt-4 border-t border-slate-800/50">
        <div class="text-[9px] font-mono text-slate-500 uppercase tracking-widest mb-3">Risk Mitigation</div>
        <div class="space-y-2">
          @for (step of mitigation; track $index) {
            <div class="flex items-start gap-2">
              <span class="text-amber-500 text-[10px] mt-0.5">▶</span>
              <span class="text-xs text-slate-400 leading-tight">{{ step }}</span>
            </div>
          }
        </div>
      </div>
    </div>
  `
})
export class PortfolioAdviceComponent {
  @Input({ required: true }) suggestions!: PortfolioAllocation[];
  @Input({ required: true }) mitigation!: string[];
}

// frontend/src/components/PortfolioAdvice.tsx
import React from 'react';
import type { PortfolioAllocation } from '../types';
import { Briefcase, Target, ShieldCheck } from 'lucide-react';

export const PortfolioAdvice: React.FC<{ suggestions: PortfolioAllocation[], risks: string[] }> = ({ suggestions, risks }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-12 mb-12">
      <div className="bg-slate-800 p-6 rounded-lg shadow-lg border-t-4 border-emerald-500">
        <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-emerald-400">
          <Briefcase size={24} /> Actionable Portfolio Allocation
        </h2>
        <div className="space-y-4">
          {suggestions.map((s, i) => (
            <div key={i} className="flex justify-between items-start gap-4 p-4 bg-slate-900/40 rounded border border-slate-700">
              <div className="flex-1">
                <h3 className="font-bold text-slate-100">{s.asset_class}</h3>
                <p className="text-xs text-slate-400 mt-1">{s.rationale}</p>
              </div>
              <div className="text-xl font-mono font-black text-emerald-400 min-w-[60px] text-right">
                {s.percentage}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-slate-800 p-6 rounded-lg shadow-lg border-t-4 border-blue-500">
        <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-blue-400">
          <ShieldCheck size={24} /> Risk Mitigation Steps
        </h2>
        <ul className="space-y-4">
          {risks.map((r, i) => (
            <li key={i} className="flex gap-3 items-start p-3 bg-slate-900/40 rounded border border-slate-700">
              <div className="mt-1">
                <Target size={18} className="text-blue-500" />
              </div>
              <span className="text-sm text-slate-200">{r}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};
