// frontend/src/components/CreditPanel.tsx
import React from 'react';
import type { CreditHealth } from '../types';
import { AlertCircle, Landmark } from 'lucide-react';

export const CreditPanel: React.FC<{ data: CreditHealth }> = ({ data }) => {
  return (
    <div className="bg-slate-800 p-6 rounded-lg shadow-lg">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-bold flex items-center gap-2 text-rose-400">
          <Landmark size={24} /> Credit & Mid-Cap Health
        </h2>
        {data.alert && (
          <div className="bg-rose-500/20 text-rose-500 px-3 py-1 rounded-full text-xs font-bold border border-rose-500/50 flex items-center gap-1 animate-pulse">
            <AlertCircle size={14} /> ICR ALERT
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <div className="bg-slate-900/40 p-4 rounded border border-slate-700">
          <span className="text-slate-400 text-sm">Avg Mid-Cap ICR</span>
          <p className={`text-2xl font-mono font-bold mt-1 ${data.mid_cap_avg_icr < 1.5 ? 'text-rose-500' : 'text-emerald-400'}`}>
            {data.mid_cap_avg_icr.toFixed(2)}x
          </p>
        </div>
        <div className="bg-slate-900/40 p-4 rounded border border-slate-700 col-span-2">
          <div className="flex gap-4 overflow-x-auto pb-2">
            {data.sectoral_breakdown.map((s, i) => (
              <div key={i} className="min-w-[120px] border-r border-slate-700/50 last:border-0 pr-4">
                <span className="text-[10px] uppercase tracking-wider text-slate-500">{s.sector}</span>
                <p className={`text-sm font-mono mt-1 ${s.average_icr < 1.5 ? 'text-rose-400' : 'text-slate-200'}`}>
                  {s.average_icr.toFixed(2)}x
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-8">
        {[
          { label: 'PIK Debt', val: data.pik_debt_issuance },
          { label: 'CRE Delinq.', val: data.cre_delinquency_rate },
          { label: 'HY OAS', val: data.mid_cap_hy_oas },
          { label: 'CP Spreads', val: data.cp_spreads },
          { label: 'CDX (VIX-C)', val: data.vix_of_credit_cdx }
        ].map((m, i) => (
          <div key={i} className="bg-slate-900/30 p-2 rounded border border-slate-700/50 text-center">
            <span className="text-[9px] text-slate-500 font-bold uppercase block">{m.label}</span>
            <span className="text-xs font-mono text-slate-300 block mt-1">{m.val}</span>
          </div>
        ))}
      </div>

      <div>
        <h3 className="text-sm font-bold text-slate-400 mb-3 uppercase tracking-widest">High-Risk Watchlist (ICR &lt; 1.2x)</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="text-slate-500 border-b border-slate-700">
                <th className="pb-2 text-left">Firm</th>
                <th className="pb-2 text-left">Debt Load</th>
                <th className="pb-2 text-left">ICR</th>
                <th className="pb-2 text-left">Insider Activity</th>
                <th className="pb-2 text-left">CDS Pricing</th>
              </tr>
            </thead>
            <tbody>
              {data.watchlist.map((f, i) => (
                <tr key={i} className="border-b border-slate-700/30">
                  <td className="py-2 font-bold">{f.firm_name}</td>
                  <td className="py-2 text-slate-400 font-mono">{f.debt_load}</td>
                  <td className="py-2 text-rose-400 font-mono">{f.icr.toFixed(2)}x</td>
                  <td className="py-2 italic text-slate-300">{f.insider_selling}</td>
                  <td className="py-2 text-slate-400 font-mono">{f.cds_pricing}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

// frontend_angular/src/app/components/ui/credit-panel.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CreditHealth } from '../../models/dashboard.models';

@Component({
  selector: 'app-credit-panel',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-[#0f172a] rounded-xl border border-slate-800 p-6 shadow-xl space-y-6">
      <div class="flex items-center justify-between border-b border-slate-800 pb-4">
        <div class="flex items-center gap-3">
          <div class="text-red-500 font-bold">&#33;</div>
          <h2 class="font-display text-2xl tracking-wider text-slate-100 uppercase">Credit & Debt Watch</h2>
        </div>
        <div *ngIf="data.alert" class="px-2 py-0.5 rounded bg-red-500/10 border border-red-500/20 text-[10px] text-red-400 font-bold uppercase tracking-widest">
          High Stress Signal
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <!-- Core Stats -->
        <div class="space-y-4">
          <div class="p-4 rounded-lg bg-slate-900/50 border border-slate-800">
            <div class="text-[10px] text-slate-500 uppercase tracking-widest font-mono mb-1">Mid-Cap Avg ICR</div>
            <div class="flex items-baseline gap-2">
              <span class="text-3xl font-display text-slate-100">{{ data.mid_cap_avg_icr }}x</span>
              <span [class]="data.mid_cap_avg_icr < 2.5 ? 'text-red-400' : 'text-emerald-400'" class="text-xs font-mono">
                {{ data.mid_cap_avg_icr < 2.5 ? 'CRITICAL' : 'STABLE' }}
              </span>
            </div>
          </div>
          
          <div class="grid grid-cols-2 gap-4">
            <div class="p-3 rounded-lg bg-slate-900/30 border border-slate-800">
              <div class="text-[9px] text-slate-500 uppercase tracking-widest font-mono">CRE Delinquency</div>
              <div class="text-lg font-display text-slate-200">{{ data.cre_delinquency_rate }}</div>
            </div>
            <div class="p-3 rounded-lg bg-slate-900/30 border border-slate-800">
              <div class="text-[9px] text-slate-500 uppercase tracking-widest font-mono">PIK Issuance</div>
              <div class="text-lg font-display text-slate-200">{{ data.pik_debt_issuance }}</div>
            </div>
          </div>
        </div>

        <!-- Sector Breakdown -->
        <div class="md:col-span-2 space-y-4">
          <div class="text-[10px] text-slate-500 uppercase tracking-widest font-mono border-l-2 border-amber-500 pl-2">Sectoral ICR Analysis</div>
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-3">
            @for (s of data.sectoral_breakdown; track s.sector) {
              <div class="p-3 rounded bg-slate-900/20 border border-slate-800/50 flex flex-col gap-1">
                <div class="text-[9px] text-slate-400 truncate font-mono uppercase">{{ s.sector }}</div>
                <div class="flex items-center justify-between">
                  <span class="text-sm font-bold text-slate-200">{{ s.average_icr }}x</span>
                  <span *ngIf="s.status === 'DISTRESSED'" class="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse"></span>
                </div>
              </div>
            }
          </div>
        </div>
      </div>

      <!-- Watchlist -->
      <div *ngIf="data.watchlist.length > 0" class="space-y-3">
        <div class="text-[10px] text-slate-500 uppercase tracking-widest font-mono border-l-2 border-red-500 pl-2">Individual Firm Watchlist</div>
        <div class="overflow-x-auto">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="text-[9px] text-slate-500 uppercase tracking-widest font-mono border-b border-slate-800">
                <th class="py-2">Firm</th>
                <th class="py-2">ICR</th>
                <th class="py-2">Debt Load</th>
                <th class="py-2">CDS Pricing</th>
              </tr>
            </thead>
            <tbody class="text-xs font-mono">
              @for (f of data.watchlist; track f.firm_name) {
                <tr class="border-b border-slate-900 hover:bg-slate-900/20 transition-colors">
                  <td class="py-3 text-slate-200">{{ f.firm_name }} <span class="text-[9px] text-slate-500">({{ f.ticker || 'N/A' }})</span></td>
                  <td class="py-3" [class.text-red-400]="f.icr < 1.5">{{ f.icr }}x</td>
                  <td class="py-3 text-slate-400">{{ f.debt_load }}</td>
                  <td class="py-3 text-slate-400">{{ f.cds_pricing }}</td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `
})
export class CreditPanelComponent {
  @Input({ required: true }) data!: CreditHealth;
}
